version: "3.7"
services:
  ui:
    # network_mode: host
    container_name: ui
    image: registry.cn-shenzhen.aliyuncs.com/algesthesiahunter/algesthesiahunter-ui:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/Users/liulu/Documents/website/sslforfree:/ssl"
  api:
    container_name: api
    image: registry.cn-shenzhen.aliyuncs.com/algesthesiahunter/algesthesiahunter-api:latest
    ports:
      - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - "/Users/liulu/Documents/website/data:/data"
  # mysql:
  #   network_mode: host
  #   container_name: mysql
  #   image: mysql:5.7
  #   volumes:
  #     - "./data/mysql/conf:/etc/mysql/conf.d"
  #     - "./data/mysql/logs:/logs"
  #     - "./data/mysql/data:/var/lib/mysql"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysql123
  # redis:
  #   network_mode: host
  #   container_name: redis
  #   image: redis:4.0.8-alpine
  #   volumes:
  #     - "./data/redis/conf:/conf/"
  #     - "./data/redis/data:/data"
  #   command:
  #     - /conf/redis.conf
  #     - --appendonly
  #     - "yes"
  # nats-streaming:
  #   network_mode: host
  #   container_name: nats-streaming
  #   image: nats-streaming:0.11.2
  #   volumes:
  #     - "./data/nats-streaming/datastrore:/datastrore"
  #   command:
  #     - --auth
  #     - NATS12345
  #     - --cluster_id
  #     - test-cluster
  #     - -p
  #     - "4222"
  #     - -m
  #     - "8222"
  #     - -store
  #     - file
  #     - -dir
  #     - datastore
